### ISSUE TITLE
Cellery hub details page of the cell image title should be changed to <Org>/<ImageName>:<Version> 

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/cellery-hub#94]
Currently the title and version is separated with '-'. Eg: `wso2cellery/pet-be-zero-scale-cell - latest`

But generally in the syntax, and cellery commands we use `wso2cellery/pet-be-zero-scale-cell:latest` which is separated by ':'. Therefore, it will be better to adjust the title of that page accordingly to be consistent.

**Comment by Minoli** [comment]
Fixed with https://github.com/wso2-cellery/cellery-hub/pull/96/commits/7c8357c1579e2d74d7486301262d38476199bfb4
